name: totem_boschetto
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter_svg: ^2.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Black.ttf
      - asset: assets/fonts/Inter-Bold.ttf
        weight: 800
      - asset: assets/fonts/Inter-ExtraBold.ttf
        weight: 900
      - asset: assets/fonts/Inter-Light.ttf
        weight: 200
      - asset: assets/fonts/Inter-Medium.ttf
        weight: 500
      - asset: assets/fonts/Inter-Regular.ttf
  uses-material-design: true


assets:
  - assets/icons/
  - assets/icons/statistics/
  - assets/images/

